-- =============================================================
-- Migration: 20260413000006_plg_monetization
-- Ticket: MMC-18 — PLG and monetization (share links, credit
-- ledger, org subscriptions)
--
-- Key design decisions:
--   - Stripe is the v0 payment processor (ADR 012); org_subscriptions
--     carries Stripe-specific external IDs. Schema is designed to
--     accommodate migration to Paddle later with minimal changes.
--   - credit_ledger is append-only; balance_after is denormalized
--     for fast balance lookup. idempotency_key prevents
--     double-writes on retry for deductions.
--   - share_link_views captures viewer_user_id (nullable FK to
--     auth.users) so logged-in Hermes users are identified on
--     view. Anonymous viewers are tracked by viewer_session_id.
--   - share_links support optional password protection and
--     expiry; soft-disable via is_active preserves view history.
--
-- Table creation order (dependency chain):
--   share_links → share_link_views
--   credit_ledger (references deals, analysis_jobs — both optional)
--   org_subscriptions (references organizations)
--
-- Rollback: supabase/migrations/rollback/20260413000006_rollback.sql
-- =============================================================


-- =============================================================
-- TABLE: share_links
-- DocSend-style shareable links for external deal sharing.
-- A link can point to a deal summary, a specific model result,
-- or a full IC package.
--
-- token: short random string used as the URL key (/share/<token>).
--   Generated by the application, stored here for lookup.
-- link_type:
--   deal_summary   — deal overview without financial model
--   model_result   — a specific model result (composition + output)
--   ic_package     — full IC-grade output with scenario set
-- password_hash: bcrypt hash; null if no password required.
-- is_active: soft-disable preserves view history on the link.
-- =============================================================

CREATE TABLE public.share_links (
  id               uuid        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  deal_id          uuid        NOT NULL REFERENCES public.deals(id) ON DELETE CASCADE,
  org_id           uuid        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  model_result_id  uuid        REFERENCES public.model_results(id) ON DELETE SET NULL,
  created_by       uuid        NOT NULL REFERENCES auth.users(id),
  token            text        NOT NULL UNIQUE,
  link_type        text        NOT NULL
                     CHECK (link_type IN ('deal_summary','model_result','ic_package')),
  is_active        boolean     NOT NULL DEFAULT true,
  expires_at       timestamptz,
  password_hash    text,
  created_at       timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT model_result_required_for_type CHECK (
    (link_type IN ('model_result','ic_package') AND model_result_id IS NOT NULL)
    OR link_type = 'deal_summary'
  )
);

ALTER TABLE public.share_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can manage their share links"
  ON public.share_links
  FOR ALL
  TO authenticated
  USING (org_id = ANY(auth.user_org_ids()));

CREATE INDEX idx_share_links_deal_id
  ON public.share_links (deal_id);

CREATE INDEX idx_share_links_token
  ON public.share_links (token)
  WHERE is_active = true;


-- =============================================================
-- TABLE: share_link_views
-- One row per view event — engagement analytics for share links.
--
-- viewer_session_id: opaque UUID for the viewer's browser
--   session. Set by the application on first view; persisted in
--   the viewer's browser storage. Identifies the same anonymous
--   viewer across multiple view events.
-- viewer_user_id: nullable FK to auth.users. Populated when the
--   viewer is a logged-in Hermes user, allowing "did our LP
--   already look at this deal?" queries.
-- viewer_email / viewer_name: nullable; captured when the viewer
--   identifies themselves or is required to before viewing.
-- page_or_section: which section of the shared document they
--   viewed, for engagement heatmap tracking.
-- time_spent_seconds: dwell time on that section.
-- =============================================================

CREATE TABLE public.share_link_views (
  id                   uuid        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  share_link_id        uuid        NOT NULL REFERENCES public.share_links(id) ON DELETE CASCADE,
  viewer_session_id    text        NOT NULL,
  viewer_user_id       uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  viewer_email         text,
  viewer_name          text,
  ip_address           text,
  user_agent           text,
  page_or_section      text,
  time_spent_seconds   integer     CHECK (time_spent_seconds IS NULL OR time_spent_seconds >= 0),
  viewed_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.share_link_views ENABLE ROW LEVEL SECURITY;

-- Org members can read view data for their own share links
CREATE POLICY "Org members can read views for their share links"
  ON public.share_link_views
  FOR SELECT
  TO authenticated
  USING (
    share_link_id IN (
      SELECT id FROM public.share_links
      WHERE org_id = ANY(auth.user_org_ids())
    )
  );

-- Anonymous inserts happen via service role (no RLS policy needed
-- for INSERT — service role bypasses RLS)

CREATE INDEX idx_share_link_views_share_link_id
  ON public.share_link_views (share_link_id);

CREATE INDEX idx_share_link_views_viewer_session
  ON public.share_link_views (viewer_session_id);

CREATE INDEX idx_share_link_views_viewer_user
  ON public.share_link_views (viewer_user_id)
  WHERE viewer_user_id IS NOT NULL;


-- =============================================================
-- TABLE: credit_ledger
-- Append-only ledger of every credit transaction for an org.
-- Credits are the usage currency for all AI and compute events.
--
-- entry_type:
--   purchase   — credits bought by the org (Stripe payment)
--   grant      — credits granted by Hermes (trial, promo, support)
--   deduction  — credits consumed by a job or model run
--   refund     — credits returned (failed job, dispute)
--   expiry     — credits expired per plan terms
--
-- amount: positive for credits in (purchase/grant/refund),
--   negative for credits out (deduction/expiry).
-- balance_after: running balance snapshot at time of entry.
--   Denormalized for fast "what is this org's current balance?"
--   queries without summing the entire ledger.
-- idempotency_key: required for deductions; prevents double-
--   writes on job retry. Application must generate and persist
--   this key before writing the deduction.
--
-- Append-only by convention: no UPDATE or DELETE policies.
-- Service role writes only; org members can read their ledger.
-- =============================================================

CREATE TABLE public.credit_ledger (
  id                uuid        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id            uuid        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  deal_id           uuid        REFERENCES public.deals(id) ON DELETE SET NULL,
  analysis_job_id   uuid        REFERENCES public.analysis_jobs(id) ON DELETE SET NULL,
  entry_type        text        NOT NULL
                      CHECK (entry_type IN ('purchase','grant','deduction','refund','expiry')),
  amount            numeric(12,4) NOT NULL,
  balance_after     numeric(12,4) NOT NULL,
  description       text        NOT NULL,
  idempotency_key   text        UNIQUE,
  created_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT deduction_requires_idempotency_key CHECK (
    entry_type != 'deduction' OR idempotency_key IS NOT NULL
  ),
  CONSTRAINT credits_in_positive CHECK (
    entry_type NOT IN ('purchase','grant','refund') OR amount > 0
  ),
  CONSTRAINT credits_out_negative CHECK (
    entry_type NOT IN ('deduction','expiry') OR amount < 0
  )
);

ALTER TABLE public.credit_ledger ENABLE ROW LEVEL SECURITY;

-- Org members can read their own ledger (service role handles writes)
CREATE POLICY "Org members can read their credit ledger"
  ON public.credit_ledger
  FOR SELECT
  TO authenticated
  USING (org_id = ANY(auth.user_org_ids()));

CREATE INDEX idx_credit_ledger_org_id
  ON public.credit_ledger (org_id, created_at DESC);

CREATE INDEX idx_credit_ledger_deal_id
  ON public.credit_ledger (deal_id)
  WHERE deal_id IS NOT NULL;

CREATE INDEX idx_credit_ledger_job_id
  ON public.credit_ledger (analysis_job_id)
  WHERE analysis_job_id IS NOT NULL;


-- =============================================================
-- TABLE: org_subscriptions
-- Subscription tier and billing state for each org.
-- One active subscription per org; historical rows (canceled)
-- are retained for audit.
--
-- plan_key:
--   free         — no payment, limited credits
--   starter      — entry-level paid tier
--   professional — full-featured paid tier
--   enterprise   — custom pricing, invoice-based
--
-- status:
--   trialing    — within trial period, access granted
--   active      — paid and current
--   past_due    — payment failed; Stripe dunning in progress
--   canceled    — canceled by user or non-payment
--   paused      — manually paused (e.g. support action)
--
-- monthly_credit_allowance: credits granted per billing cycle
--   for this plan. Applied by the application when Stripe fires
--   invoice.paid (or on cycle reset for free plans).
--
-- stripe_subscription_id / stripe_customer_id: Stripe-specific
--   external references. Nullable to support enterprise orgs
--   on manual invoicing. Per ADR 012, these can be replaced with
--   Paddle equivalents if payment infrastructure changes.
-- =============================================================

CREATE TABLE public.org_subscriptions (
  id                        uuid        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                    uuid        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  plan_key                  text        NOT NULL
                              CHECK (plan_key IN ('free','starter','professional','enterprise')),
  status                    text        NOT NULL
                              CHECK (status IN ('trialing','active','past_due','canceled','paused')),
  billing_period            text        NOT NULL DEFAULT 'monthly'
                              CHECK (billing_period IN ('monthly','annual')),
  monthly_credit_allowance  numeric(12,4) NOT NULL DEFAULT 0
                              CHECK (monthly_credit_allowance >= 0),
  stripe_subscription_id    text        UNIQUE,
  stripe_customer_id        text,
  current_period_start      timestamptz,
  current_period_end        timestamptz,
  canceled_at               timestamptz,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_org_subscriptions_updated_at
  BEFORE UPDATE ON public.org_subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.org_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can read their subscription"
  ON public.org_subscriptions
  FOR SELECT
  TO authenticated
  USING (org_id = ANY(auth.user_org_ids()));

CREATE INDEX idx_org_subscriptions_org_id
  ON public.org_subscriptions (org_id);

CREATE INDEX idx_org_subscriptions_stripe_customer
  ON public.org_subscriptions (stripe_customer_id)
  WHERE stripe_customer_id IS NOT NULL;

-- Partial index: fast lookup of the active subscription for an org
CREATE INDEX idx_org_subscriptions_active
  ON public.org_subscriptions (org_id, status)
  WHERE status IN ('trialing','active','past_due');
